import Head from 'next/head'
import Paralx from '../components/Paralx'
import Slider from '../components/Slide'
import { SliderData } from '../components/SliderData'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Job App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paralx heading="Heading for this page" text="just random text, and its pretty long so be that wazz wawdsada asdas adw asd aaw das"/>
      <Slider slides={SliderData}/>

    </div>
  )
}
